name: Build with Maven (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build with Maven Wrapper
        run: ..\mvnw.cmd verify $MAVEN_PROFILES $ADDITIONAL_MAVEN_ARGS
        working-directory: coin-collection-manager-aggregator
        env: 
          MAVEN_PROFILES: -Pskip-testcontainers
          ADDITIONAL_MAVEN_ARGS: 