name: Build with Maven (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build with Maven Wrapper
        run: ..\mvnw.cmd test $MAVEN_PROFILES
        working-directory: coin-collection-manager-ui
        env: 
          MAVEN_PROFILES: -PGuitest
      - name: Generate JUnit Report
        if: ${{ failure() }}
        run: ../mvnw surefire-report:report-only site:site -DgenerateReports=false
        working-directory: coin-collection-manager-ui
      - name: Archive JUnit Report
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: junit-report
          path: '**/target/site'
      - name: Archive failed GUI test screenshot
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: failed-gui-tests-screenshot
          path: '**/failed-gui-tests'